// YouTube via googleapis (discovery) + youtube-chat (parsing/emotes)
export async function initYouTube(emit) {
  let googleapis;
  let YouTubeChat;
  try {
    googleapis = await import("googleapis");
    YouTubeChat = await import("youtube-chat");
  } catch (e) {
    console.warn("[youtube] googleapis or youtube-chat not installed. Skipping.");
    return;
  }
  const { google } = googleapis;
  const { LiveChat } = YouTubeChat;

  const apiKey = process.env.YOUTUBE_API_KEY;

  // Load local YouTube emote map (generated by script)
  let YOUTUBE_EMOJI_MAP = {};
  try {
      const { readFileSync } = await import('fs');
      const path = await import('node:path');
      const { fileURLToPath } = await import('node:url');
      const __dirname = path.dirname(fileURLToPath(import.meta.url));
      
      const mapPath = path.join(__dirname, '..', 'data', 'youtube_emotes.json');
      const content = readFileSync(mapPath, 'utf8');
      YOUTUBE_EMOJI_MAP = JSON.parse(content);
      console.log(`[youtube] loaded ${Object.keys(YOUTUBE_EMOJI_MAP).length} native emotes from file.`);
  } catch (e) {
      console.warn("[youtube] failed to load youtube_emotes.json, falling back to minimal map:", e.message);
      YOUTUBE_EMOJI_MAP = {
          ":smile:": "🙂",
          ":face-purple-crying:": "https://yt3.ggpht.com/g6_km98AfdHbN43gvEuNdZ2I07MmzVpArLwEvNBwwPqpZYzszqhRzU_DXALl11TchX5_xFE=w24-h24-c-k-nd",
          ":eyes-purple-crying:": "https://yt3.ggpht.com/g6_km98AfdHbN43gvEuNdZ2I07MmzVpArLwEvNBwwPqpZYzszqhRzU_DXALl11TchX5_xFE=w24-h24-c-k-nd"
      };
  }

  if (!apiKey) {
    console.log("[youtube] missing YOUTUBE_API_KEY; skipping.");
    return;
  }
  
  const youtube = google.youtube({ version: "v3", auth: apiKey });

  // Configuration
  const envLiveChatId = process.env.YOUTUBE_LIVE_CHAT_ID; // Fallback or strict
  const channelId = process.env.YOUTUBE_CHANNEL_ID;
  const channelHandle = process.env.YOUTUBE_HANDLE || "SouHerrmann"; 

  // State
  let liveChatInstance = null;
  let isConnecting = false;
  let validationTimer = null;
  let currentVideoId = null;

  // --- Discovery Helper (Google APIs) ---

  async function getChannelIdFromHandle(handle) {
    try {
      if (!handle) return null;
      const h = handle.startsWith('@') ? handle : `@${handle}`;
      const res = await youtube.channels.list({ part: ['id'], forHandle: h });
      return res.data.items?.[0]?.id || null;
    } catch (e) {
      console.warn("[youtube] failed to resolve handle:", e.message);
      return null;
    }
  }

  // --- Connection Logic (youtube-chat) ---

  function mapMessageItems(items) {
    if (!items || !Array.isArray(items)) return [];
    
    return items.flatMap(item => {
      // 1) Custom Emoji (Channel Members/SuperChat)
      if (item.customEmoji) {
        // Try to get the biggest image (usually last) or 48x48
        const thumbs = item.customEmoji.image?.thumbnails || [];
        const url = thumbs.length ? thumbs[thumbs.length - 1].url : item.customEmoji.url;
        
        const alt = item.emojiText || item.customEmoji.shortcuts?.[0] || ":emote:";
        if (url) return [{ type: "emoji", url, alt }];
      }
      
      // 2) Text (possible standard emojis inside)
      const txt = item.text || item.emojiText || "";
      if (!txt) return [];

      // Regex to find and replace mapped Unicode/Native emojis
      // Iterate over the text and split by found emojis
      const parts = [];
      
      // Build regex from map keys
      const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const emojiKeys = Object.keys(YOUTUBE_EMOJI_MAP).sort((a,b)=>b.length - a.length);
      
      if (emojiKeys.length === 0) {
          return [{ type: "text", text: txt }];
      }

      const re = new RegExp(`(${emojiKeys.map(escapeRegExp).join("|")})`, "g");
      
      let lastIndex = 0;
      let match;
      
      while ((match = re.exec(txt)) !== null) {
          const matchStart = match.index;
          const matchStr = match[1];
          
          // Push preceding text
          if (matchStart > lastIndex) {
              parts.push({ type: "text", text: txt.slice(lastIndex, matchStart) });
          }
          
          // Push emoji
          const mapped = YOUTUBE_EMOJI_MAP[matchStr];
          if (mapped.startsWith("http")) {
              parts.push({ type: "emoji", url: mapped, alt: matchStr });
          } else {
              parts.push({ type: "text", text: mapped }); // Mapped to unicode
          }
          
          lastIndex = matchStart + matchStr.length;
      }
      
      // Remaining text
      if (lastIndex < txt.length) {
          parts.push({ type: "text", text: txt.slice(lastIndex) });
      }
      
      return parts.length ? parts : [{ type: "text", text: txt }];
    });
  }

  async function connectToStream(videoId) {
    if (liveChatInstance) {
        liveChatInstance.stop();
        liveChatInstance = null;
    }

    console.log(`[youtube] connecting scraper to video ${videoId}...`);
    try {
        const chat = new LiveChat({ liveId: videoId });
        
        chat.on("start", (liveId) => {
            console.log(`[youtube] connected to chat for ${liveId}`);
        });

        chat.on("end", (reason) => {
            console.log(`[youtube] chat ended: ${reason}`);
            scheduleValidation();
        });

        chat.on("error", (err) => {
            console.warn("[youtube] chat error:", err);
        });

        chat.on("chat", (msg) => {
             // console.log('[youtube] raw msg:', JSON.stringify(msg)); 
             const authorName = msg.author?.name || "YouTube User";
             
             // Badges
             const badges = [];
             if (msg.author?.isOwner) badges.push("owner");
             if (msg.author?.isModerator) badges.push("mod");
             if (msg.author?.isVerified) badges.push("verified");
             if (msg.author?.badge?.label?.toLowerCase().includes("member")) badges.push("member");

             // Parts mapping
             const parts = mapMessageItems(msg.message);
             const fullText = parts.map(p => p.type==='emoji' ? (p.alt||"") : p.text).join("");

             emit({
               platform: "youtube",
               author: authorName,
               text: fullText,
               parts: parts,
               badges: badges,
               avatar: msg.author?.thumbnail?.url || null,
               timestamp: msg.timestamp ? new Date(msg.timestamp).getTime() : Date.now(),
               type: 'chat'
             });
        });
        
        // Handle SuperChats/Stickers if feasible. 
        // youtube-chat emits "superchat" event? No, usually "chat" with checks or specific events?
        // Library documentation says: chat.on("superchat", (msg) => ...) works.
        
        chat.on("superchat", (msg) => {
            const authorName = msg.author?.name || "SuperChat User";
            const parts = mapMessageItems(msg.message);
            const fullText = parts.map(p => p.type==='emoji' ? p.alt : p.text).join("");
            
            emit({
                platform: "youtube",
                author: authorName,
                text: fullText,
                parts: parts,
                badges: [], // author badges maybe inside msg.author
                avatar: msg.author?.thumbnail?.url || null,
                timestamp: Date.now(),
                type: 'superchat',
                payment: {
                    amount: msg.amount || 0, // library parses this?
                    currency: msg.currency || "",
                    formatted: msg.amountString || ""
                }
            });
        });

        // Start
        const ok = await chat.start();
        if (!ok) {
            console.warn("[youtube] failed to start chat listener.");
            scheduleValidation();
            return;
        }
        liveChatInstance = chat;
        currentVideoId = videoId;
        
    } catch (e) {
        console.warn("[youtube] scraper exception:", e);
        scheduleValidation();
    }
  }

  // --- Main Loop ---

  async function validate() {
    // If we are already running, do nothing
    if (liveChatInstance) return;

    // Resolve Channel ID if needed (and if possible)
    let targetChannelId = channelId;
    if (!targetChannelId && channelHandle && !process.env.YOUTUBE_CHANNEL_ID) {
         // Try to resolve via API if we haven't yet, but if quota is dead, we might fail.
         // If we fail, we can't proceed unless we hardcode it or user adds it to env.
         // However, if we previously found it, maybe we can resort to scraping?
         // For now, let's hope API works OR user put ID in .env.
         const resolved = await getChannelIdFromHandle(channelHandle);
         if (resolved) targetChannelId = resolved;
    }

    // Fallback: If API failed but we have a handle, maybe youtube-chat supports handle? 
    // Usually no, but let's try passing it if we lack ID. 
    // Or if we have a hardcoded fallback from the logs `UC-zEotsGT3fNPzuoK87K9OA` (SouHerrmann).
    if (!targetChannelId && channelHandle.toLowerCase() === 'souherrmann') {
        targetChannelId = 'UC-zEotsGT3fNPzuoK87K9OA'; // Hardcode known ID to bypass Quota/Discovery issue
    }

    if (!targetChannelId && !envLiveChatId) {
        console.warn("[youtube] Waiting for Channel ID resolution...");
        scheduleValidation(60000);
        return;
    }

    // Prefer youtube-chat's internal discovery methods (SCRAING) over API (QUOTA)
    // If we have an ID, we can initialize LiveChat with it, and it finds the current stream.
    
    if (targetChannelId) {
        // Use youtube-chat discovery (No Quota)
         await connectToStream({ channelId: targetChannelId });
    } else if (envLiveChatId) {
         await connectToStream({ liveId: envLiveChatId });
    }
  }

  async function connectToStream(options) {
    if (liveChatInstance) {
        liveChatInstance.stop();
        liveChatInstance = null;
    }

    const label = options.channelId || options.liveId;
    console.log(`[youtube] connecting scraper to ${label} (scraped)...`);
    
    try {
        // youtube-chat constructor: { channelId } OR { liveId }
        const chat = new LiveChat(options);
        
        chat.on("start", (liveId) => {
            console.log(`[youtube] connected to chat for liveId: ${liveId}`);
        });

        chat.on("end", (reason) => {
            console.log(`[youtube] chat ended: ${reason}`);
            liveChatInstance = null; // Ensure we clear it
            scheduleValidation(10000);
        });

        chat.on("error", (err) => {
            console.warn("[youtube] chat error:", err?.message || err);
            // If it's a critical start error, we might need to reset
            // But usually the library keeps trying or emits 'end'.
        });

        chat.on("chat", (msg) => {
             // console.log('[youtube] raw msg:', JSON.stringify(msg)); 
             const authorName = msg.author?.name || "YouTube User";
             
             // Badges
             const badges = [];
             if (msg.author?.isOwner) badges.push("owner");
             if (msg.author?.isModerator) badges.push("mod");
             if (msg.author?.isVerified) badges.push("verified");
             if (msg.author?.badge?.label?.toLowerCase().includes("member")) badges.push("member");

             // Parts mapping
             const parts = mapMessageItems(msg.message);
             const fullText = parts.map(p => p.type==='emoji' ? (p.alt||"") : p.text).join("");

             emit({
               platform: "youtube",
               author: authorName,
               text: fullText,
               parts: parts,
               badges: badges,
               avatar: msg.author?.thumbnail?.url || null,
               timestamp: msg.timestamp ? new Date(msg.timestamp).getTime() : Date.now(),
               type: 'chat'
             });
        });
        
        // Start
        const ok = await chat.start();
        if (!ok) {
            console.warn("[youtube] failed to locate live stream via scraper.");
            scheduleValidation(60000); // Retry later
            return;
        }
        liveChatInstance = chat;
        
    } catch (e) {
        console.warn("[youtube] scraper exception:", e?.message);
        scheduleValidation(60000);
    }
  }

  function scheduleValidation(ms = 30000) {
      if (validationTimer) clearTimeout(validationTimer);
      validationTimer = setTimeout(validate, ms);
  }

  console.log("[youtube] initializing (scraper mode)... ");
  validate();
}
